### PR TITLE
feat: list all applications

### LINKED ISSUE #737: List an owner applications
We should be able to list an owner applications. 

This is currently possible threw the following `cURL` command:

```
clever curl https://api.clever-cloud.com/v2/organisations/<owner_id>/applications | jq '.[].name'
```

### PR DESCRIPTION
**Pull request by davlgd**
fixes #737

### CODE REVIEW

**Comment by aurrelhebert** [comment]
We could discuss about something to have the same behavior for: 
```sh
clever applications list
clever addon list
```

On usage, I would prefer a `clever applications list --org orga_XXX` over `clever applications --all orga_XXX`

For the rest: 
  - I really like the Human view, really nice job!
  - LGTM for the JSON format

**Comment by davlgd** [comment]
@hsablonniere I'll let you check everything is ok with your test org. It seems fine here.

**Comment by aurrelhebert** [comment]
LGTM, only one tiny question, should we update the --org description for this command (as it include an alternative behavior?)

**Comment by davlgd** [comment]
> LGTM, only one tiny question, should we update the --org description for this command (as it includes an alternative behavior?)

```
Organisation to target by its ID (or name, if unambiguous)
```

Seems good to me. If we want to change it we need to create another option, maybe we'll be able to be more precise in such situations with the new options mechanism.

**Review by hsablonniere — APPROVED** [review]
Nice!!! LGTM :+1:

**Review by hsablonniere — CHANGES_REQUESTED** [review]
ABORT! There's a bug.

When you run `clever applications` in a repo where you have linked apps but not with the current account, it's empty.

**Review by hsablonniere — APPROVED** [review]
@aurrelhebert @davlgd @miton18 @pdesoyres-cc

We realized it was not possible to mix the existing list with the new one without messing up the old/new JSON format and having weird edge cases with the linked apps.

This PR now proposes a new `list` subcommand on `clever applications` with only `-F json` and `-o NAME/ID` to filter. The old `clever applications` command is kept as is.

**Pull request merged**
