### PR TITLE
Fix `setDedicatedBuildInstance`

### PR DESCRIPTION
**Pull request by clementd-fretlink**
It only sends the needed fields 

See #378

I'm not sure this is the best solution (I don't know the new clever-client well, maybe it provides a better way to do that?), but it works well.

### CODE REVIEW

**Comment by hsablonniere** [comment]
Thanks very much @clementd-fretlink, seems like we were sending way too much stuffs. I'll just check that we're not missing anything...

**Comment by clementd-fretlink** [comment]
I inspected the query sent by the console to get the list of needed fields. Maybe there's a better way?

**Comment by hsablonniere** [comment]
I just checked with @Keruspe and the API is actually a patch so:

* We don't need to send other data
* We can update `separateBuild` and `buildFlavor` in one call

This "bug" was introduced when we added `buildFlavor` in the payload of `GET /.../applications/{appId}`.

I'm working on a fix, this will be released today-ish...

**Comment by clementd-fretlink** [comment]
ah good. Is there something I can do on this PR?

**Comment by hsablonniere** [comment]
@divarvel Thanks very much for the PR, sorry we don't include it as is but as you can see in #380, after investigations on the API, we were able to simplify the code and the number of API calls.

**Comment by clementd-fretlink** [comment]
Ah that's even better :+1:

**Pull request closed without merging**
