### PR TITLE
WIP: Exit process with code 1 on deployment errors

### LINKED ISSUE #195: Add ⚠️ message when deploying a non-existent branch
eg:
```shell
clever deploy --branch my-killer-feature
```

```shell
😡 this 🌿 doesn't exist
```

### LINKED ISSUE #197: Error on `clever deploy` command exit code was 0
```
$ ./clever deploy
[ERROR] { Error: error authenticating: no auth sock variable errno: -1 }
```

Added [this code](http://blog.fgribreau.com/2018/02/continuous-deployment-on-clevercloud.html) to a new project, `clever deploy` did exit with `0`, I think it should not, am I right?

### PR DESCRIPTION
**Pull request by hsablonniere**
This commit required a pretty big refactor:

* Enforce ES6 features (const, fat arrows, destructuring...)
* Try to harmonize and unify Bacon streams (and error handling)
* Safer usage of "colors" package

Fixes #195
Fixes #197

### CODE REVIEW

**Comment by divarvel** [comment]
Cool! Since this part is quite complex, I think that would be a good think to take time to test it thoroughly before release (not a blocker for the merge request, though)

**Comment by hsablonniere** [comment]
Apart from the exit code, this contains a small improvement:

This is what a `clever deploy` used to log:

```
Pushing source code to Clever Cloud.
Your source code has been pushed to Clever Cloud.
Waiting for application logs…
Deployment started
Logs bla
Logs bla bla
Logs bla bla bla
Logs bla bla
Logs bla
```

Now we have the deployment successful at the end when quiet mode is false:

```
Pushing source code to Clever Cloud.
Your source code has been pushed to Clever Cloud.
Waiting for application logs…
Deployment started
Deployment successful
```

**Comment by hsablonniere** [comment]
Same thing with errors

**Comment by divarvel** [comment]
Yeah the missing "deployment success" was due to a race condition due to logs delay.

**Pull request merged**
