### PR TITLE
Fix `clever scale --build-flavor`

### LINKED ISSUE #378: clever scale --build-flavor disabled: you provided invalid application data
The help of `clever scale --help` shows that to disable the build instance, you have to pass `disabled`: `clever scare --build-flavor disabled`

But when I do this, it throws an error:
```
~ $ clever scale --build-flavor disabled
[ERROR] You provided invalid application data
```

### PR DESCRIPTION
**Pull request by hsablonniere**
Fixes #378

### CODE REVIEW

**Comment by hsablonniere** [comment]
@divarvel WDYT?

**Comment by divarvel** [comment]
I wish I could have implemented it like this the first time :-)

**Comment by hsablonniere** [comment]
I actually forgot this was an open contribution from your part.

**Comment by divarvel** [comment]
That's why I took the liberty to investigate and propose a fix ^^

**Pull request merged**
