### PR TITLE
add datadog drain target

### PR DESCRIPTION
**Pull request by KannarFr**

### CODE REVIEW

**Comment by KannarFr** [comment]
There is one error on CI can you check it and explain it @hsablonniere?

**Comment by guyzmo** [comment]
(works for me)

**Comment by KannarFr** [comment]
Tested and approved.

**Comment by guyzmo** [comment]
though it's still `-k` for the short version, so it's 👌 😉

**Comment by guyzmo** [comment]
just installed/tested the latest version, it's working fine, thank you ♥

**Pull request merged**
