### PR TITLE
chore(git): prevent fixup commits

### PR DESCRIPTION
**Pull request by miton18**

### CODE REVIEW

**Comment by hsablonniere** [comment]
@miton18 Does it mean it won't try to build the PR and the preview or will it just block the merge?

**Comment by miton18** [comment]
> @miton18 Does it mean it won't try to build the PR and the preview or will it just block the merge?

As you see, this check is in another workflow, so, the build step is not blocked.
It only block the merge of the PR

**Comment by hsablonniere** [comment]
>  It only block the merge of the PR

This is perfect!

**Review by hsablonniere — APPROVED** [review]
LGTM :+1:

**Pull request merged**
