### PR TITLE
Fix ng term

### PR DESCRIPTION
**Pull request by KannarFr**
image
Here is a full example of the results.

### CODE REVIEW

**Comment by RemiBardon** [comment]
Unless it changed, spaces before `()` in function declarations are enforced by the linter configuration, otherwise LGTM

**Comment by KannarFr** [comment]
Where is this linter configuration? I defined no linter in my editor and it auto-applied these changes.

**Comment by RemiBardon** [comment]
<https://github.com/CleverCloud/clever-tools/blob/master/.eslintrc.js> doesn't override the [`space-before-function-paren`](https://eslint.org/docs/latest/rules/space-before-function-paren) rule, which is enabled by default (<https://eslint.org/docs/latest/rules/space-before-function-paren#options>)

**Comment by RemiBardon** [comment]
I guess you can just drop 9906546058425043fa3d26eb0a569dd2621e622e to fix the eslint warnings

**Comment by KannarFr** [comment]
Done.

**Review by RemiBardon — APPROVED** [review]

**Review by hsablonniere — APPROVED** [review]

**Pull request merged**
