### PR TITLE
Bump nodegit to 0.5.0

### PR DESCRIPTION
**Pull request by urcadox**
Update nodegit to 0.5.0.

This fixes issue #10.

### CODE REVIEW

**Comment by divarvel** [comment]
Please update the tests as well :3

**Comment by urcadox** [comment]
Will do, my bad.

**Comment by urcadox** [comment]
Code fixed + one test skipped (see the TODO in the relevant commit)

**Comment by FGRibreau** [comment]
:+1: !

**Comment by divarvel** [comment]
urcadox can you update the PR to resolve the conflicts please? :3

**Comment by urcadox** [comment]
All good and ready to go :)

**Comment by FGRibreau** [comment]
@divarvel tu peux release une nouvelle version de clever-tools ? Thx :) (c'est plus user-friendly :))

**Pull request merged**
