### PR TITLE
Issue 202 error handling small commands

### PR DESCRIPTION
**Pull request by hsablonniere**
Refactor for:

* profile
* makeDefault
* ssh
* applications

### CODE REVIEW

**Comment by divarvel** [comment]
Oo a travis build issue that's actually a real issue!

**Comment by divarvel** [comment]
So the failure is that `conf.CONFIGURATION_FILE` is not used and the conf is read from `~/.config/clever-cloud`

**Comment by hsablonniere** [comment]
I forgot to run them locally :-(

**Comment by hsablonniere** [comment]
Fixed and updated!

**Pull request merged**
